version: '3.8'

services:
  app:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  web:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
    depends_on:
      - app

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a
      PGADMIN_DEFAULT_PASSWORD:
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  pgdata:
