services:
  app:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  web:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
    depends_on:
      - app

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

  node:
    image: node:20
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: npm run dev
    environment:
      - HOST=0.0.0.0
    ports:
      - '5173:5173'
    depends_on:
      - app

volumes:
  postgres-data:
  pgadmin-data:
